# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date requested')),
                ('url_rpt', models.CharField(blank=True, default='', max_length=200)),
                ('base64_audio', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ('requested',),
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(blank=True, default='na', max_length=200)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspector.Request')),
            ],
            options={
                'ordering': ('request',),
            },
        ),
    ]
