# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='transcript',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='response',
            name='response',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
