# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0002_auto_20170216_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestFly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_rpt', models.CharField(blank=True, default='', max_length=200)),
                ('base64_audio', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='ResponseFly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(blank=True, default='', max_length=200)),
                ('transcript', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
    ]
