# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0003_requestfly_responsefly'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsefly',
            name='uri_image',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
