# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 14:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0004_responsefly_uri_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responsefly',
            old_name='uri_image',
            new_name='url_image',
        ),
    ]
