# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0005_auto_20170221_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='url_rpt',
            field=models.CharField(blank=True, default=b'na', max_length=200),
        ),
        migrations.AlterField(
            model_name='requestfly',
            name='url_rpt',
            field=models.CharField(blank=True, default=b'na', max_length=200),
        ),
        migrations.AlterField(
            model_name='response',
            name='response',
            field=models.CharField(blank=True, default=b'na', max_length=200),
        ),
        migrations.AlterField(
            model_name='response',
            name='transcript',
            field=models.CharField(blank=True, default=b'na', max_length=200),
        ),
        migrations.AlterField(
            model_name='responsefly',
            name='response',
            field=models.CharField(blank=True, default=b'na', max_length=200),
        ),
        migrations.AlterField(
            model_name='responsefly',
            name='transcript',
            field=models.CharField(blank=True, default=b'na', max_length=200),
        ),
        migrations.AlterField(
            model_name='responsefly',
            name='url_image',
            field=models.CharField(blank=True, default=b'na', max_length=250),
        ),
    ]
