# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interpreter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='base64_audio',
            field=models.TextField(blank=True, default=''),
        ),
    ]
