# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interpreter', '0002_auto_20170216_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='transcript',
            field=models.CharField(blank=True, default='na', max_length=200),
        ),
    ]
