# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interpreter', '0003_response_transcript'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestFly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_analyzer', models.CharField(max_length=250)),
                ('base64_audio', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='ResponseFly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript', models.CharField(blank=True, default='na', max_length=200)),
                ('query', models.CharField(blank=True, default='na', max_length=200)),
            ],
        ),
    ]
