# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interpreter', '0005_auto_20170221_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='url_analyzer',
            field=models.CharField(default=b'na', max_length=250),
        ),
        migrations.AlterField(
            model_name='requestfly',
            name='url_analyzer',
            field=models.CharField(default=b'na', max_length=250),
        ),
    ]
