# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(choices=[(b'error_count', b'error count'), (b'warning_count', b'warning count'), (b'finished_normally', b'finished normally'), (b'cell_count', b'number of cells')], max_length=200)),
                ('url_rpt', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('url_rpt',),
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(blank=True, default='none', max_length=200)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.Query')),
            ],
            options={
                'ordering': ('query',),
            },
        ),
        migrations.CreateModel(
            name='SupportedQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(choices=[(b'error_count', b'error count'), (b'warning_count', b'warning count'), (b'finished_normally', b'finished normally'), (b'cell_count', b'number of cells')], max_length=200)),
            ],
            options={
                'ordering': ('query',),
            },
        ),
    ]
